// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-projects.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function publicSupabase() {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_projects_default = defineTool({
  name: "search_projects",
  title: "Search projects",
  description: "Search public research projects on Resona by keyword. Matches the title and abstract, optionally filtered by a tag. Returns the most recent matches.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Keyword to search titles and abstracts for."),
    tag: z.string().trim().optional().describe("Optional tag to filter results by."),
    limit: z.number().int().min(1).max(50).optional().describe("Maximum results to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, tag, limit }) => {
    const supabase = publicSupabase();
    const keyword = query.replace(/[,()]/g, " ").replace(/[\\%_]/g, "\\$&").trim();
    let request = supabase.from("projects").select("id, title, abstract, tags, author_id, created_at").eq("visibility", "public").or(`title.ilike.%${keyword}%,abstract.ilike.%${keyword}%`).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (tag) request = request.contains("tags", [tag]);
    const { data, error } = await request;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-project.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function publicSupabase2() {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_project_default = defineTool2({
  name: "get_project",
  title: "Get project",
  description: "Fetch full details for a single public research project by its id, including content, tags, links, resonance and fork counts, and comments.",
  inputSchema: {
    id: z2.string().trim().min(1).describe("The project id (UUID).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const supabase = publicSupabase2();
    const { data: project, error } = await supabase.from("projects").select("id, title, abstract, content, tags, github_url, dataset_url, author_id, source_project_id, created_at, updated_at").eq("id", id).eq("visibility", "public").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!project) return { content: [{ type: "text", text: "Project not found or not public." }], isError: true };
    const [{ count: resonanceCount }, { count: forkCount }, { data: comments }] = await Promise.all([
      supabase.from("project_resonances").select("user_id", { count: "exact", head: true }).eq("project_id", id),
      supabase.from("project_forks").select("id", { count: "exact", head: true }).eq("source_project_id", id),
      supabase.from("project_comments").select("id, content, created_at").eq("project_id", id).order("created_at", { ascending: true })
    ]);
    const result = {
      ...project,
      resonance_count: resonanceCount ?? 0,
      fork_count: forkCount ?? 0,
      comments: comments ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: { project: result }
    };
  }
});

// src/lib/mcp/tools/list-recent-projects.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function publicSupabase3() {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_recent_projects_default = defineTool3({
  name: "list_recent_projects",
  title: "List recent projects",
  description: "List the most recently published public research projects on Resona, newest first. Useful for seeing what the community is working on right now.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional().describe("Maximum results to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = publicSupabase3();
    const { data, error } = await supabase.from("projects").select("id, title, abstract, tags, author_id, created_at").eq("visibility", "public").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/resonate-project.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var resonate_project_default = defineTool4({
  name: "resonate_project",
  title: "Resonate with a project",
  description: "Resonate with (like/amplify) a public research project as the signed-in user, or remove your resonance. Returns the project's updated resonance count.",
  inputSchema: {
    project_id: z4.string().trim().min(1).describe("The project id (UUID) to resonate with."),
    resonate: z4.boolean().optional().describe("true to resonate (default), false to remove an existing resonance.")
  },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id, resonate }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const shouldResonate = resonate ?? true;
    if (shouldResonate) {
      const { error } = await supabase.from("project_resonances").upsert({ project_id, user_id: userId });
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    } else {
      const { error } = await supabase.from("project_resonances").delete().eq("project_id", project_id).eq("user_id", userId);
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const { count } = await supabase.from("project_resonances").select("user_id", { count: "exact", head: true }).eq("project_id", project_id);
    const result = {
      project_id,
      has_resonated: shouldResonate,
      resonance_count: count ?? 0
    };
    return {
      content: [
        {
          type: "text",
          text: `${shouldResonate ? "Resonated with" : "Removed resonance from"} project ${project_id}. Total resonances: ${count ?? 0}.`
        }
      ],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/fork-project.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var fork_project_default = defineTool5({
  name: "fork_project",
  title: "Fork a project",
  description: "Fork (evolve) a public research project as the signed-in user. Creates a new derivative project owned by the user and records the fork link back to the source. Returns the new project id.",
  inputSchema: {
    project_id: z5.string().trim().min(1).describe("The source project id (UUID) to fork."),
    title: z5.string().trim().optional().describe("Optional title for the fork. Defaults to 'Fork of <original title>'.")
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ project_id, title }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const userId = ctx.getUserId();
    const { data: source, error: sourceError } = await supabase.from("projects").select("id, title, abstract, content, tags, github_url, dataset_url").eq("id", project_id).eq("visibility", "public").maybeSingle();
    if (sourceError) return { content: [{ type: "text", text: sourceError.message }], isError: true };
    if (!source) {
      return { content: [{ type: "text", text: "Source project not found or not public." }], isError: true };
    }
    const { data: created, error: createError } = await supabase.from("projects").insert({
      author_id: userId,
      title: (title?.trim() || `Fork of ${source.title}`).slice(0, 255),
      abstract: source.abstract,
      content: source.content,
      tags: source.tags,
      github_url: source.github_url,
      dataset_url: source.dataset_url,
      source_project_id: source.id
    }).select("id").single();
    if (createError) return { content: [{ type: "text", text: createError.message }], isError: true };
    const { error: forkError } = await supabase.from("project_forks").insert({
      source_project_id: source.id,
      forked_project_id: created.id,
      author_id: userId
    });
    if (forkError) return { content: [{ type: "text", text: forkError.message }], isError: true };
    const result = {
      source_project_id: source.id,
      forked_project_id: created.id
    };
    return {
      content: [
        {
          type: "text",
          text: `Forked project ${source.id} into new project ${created.id}.`
        }
      ],
      structuredContent: result
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "huimhiootbkwcbhhlruj";
var mcp_default = defineMcp({
  name: "resona-mcp",
  title: "Resona MCP",
  version: "0.2.0",
  instructions: "Tools for Resona, a decentralized social network for science. Read tools (`search_projects`, `list_recent_projects`, `get_project`) work over public data. Write tools (`resonate_project`, `fork_project`) act as the signed-in user: `resonate_project` amplifies or unamplifies a project, and `fork_project` evolves a project into a new derivative owned by the user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_projects_default,
    get_project_default,
    list_recent_projects_default,
    resonate_project_default,
    fork_project_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
