// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-projects.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function publicSupabase() {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_projects_default = defineTool({
  name: "search_projects",
  title: "Search projects",
  description: "Search public research projects on Resona by keyword. Matches the title and abstract, optionally filtered by a tag. Returns the most recent matches.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Keyword to search titles and abstracts for."),
    tag: z.string().trim().optional().describe("Optional tag to filter results by."),
    limit: z.number().int().min(1).max(50).optional().describe("Maximum results to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, tag, limit }) => {
    const supabase = publicSupabase();
    let request = supabase.from("projects").select("id, title, abstract, tags, author_id, created_at").eq("visibility", "public").or(`title.ilike.%${query}%,abstract.ilike.%${query}%`).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (tag) request = request.contains("tags", [tag]);
    const { data, error } = await request;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-project.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function publicSupabase2() {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_project_default = defineTool2({
  name: "get_project",
  title: "Get project",
  description: "Fetch full details for a single public research project by its id, including content, tags, links, resonance and fork counts, and comments.",
  inputSchema: {
    id: z2.string().trim().min(1).describe("The project id (UUID).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const supabase = publicSupabase2();
    const { data: project, error } = await supabase.from("projects").select("id, title, abstract, content, tags, github_url, dataset_url, author_id, source_project_id, created_at, updated_at").eq("id", id).eq("visibility", "public").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!project) return { content: [{ type: "text", text: "Project not found or not public." }], isError: true };
    const [{ count: resonanceCount }, { count: forkCount }, { data: comments }] = await Promise.all([
      supabase.from("project_resonances").select("user_id", { count: "exact", head: true }).eq("project_id", id),
      supabase.from("project_forks").select("id", { count: "exact", head: true }).eq("source_project_id", id),
      supabase.from("project_comments").select("id, content, created_at").eq("project_id", id).order("created_at", { ascending: true })
    ]);
    const result = {
      ...project,
      resonance_count: resonanceCount ?? 0,
      fork_count: forkCount ?? 0,
      comments: comments ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: { project: result }
    };
  }
});

// src/lib/mcp/tools/list-recent-projects.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function publicSupabase3() {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_recent_projects_default = defineTool3({
  name: "list_recent_projects",
  title: "List recent projects",
  description: "List the most recently published public research projects on Resona, newest first. Useful for seeing what the community is working on right now.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional().describe("Maximum results to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = publicSupabase3();
    const { data, error } = await supabase.from("projects").select("id, title, abstract, tags, author_id, created_at").eq("visibility", "public").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "resona-mcp",
  title: "Resona MCP",
  version: "0.1.0",
  instructions: "Tools for Resona, a decentralized social network for science. Use `search_projects` to find public research projects by keyword or tag, `list_recent_projects` to browse the newest posts, and `get_project` to read a project's full content and interaction counts.",
  tools: [search_projects_default, get_project_default, list_recent_projects_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
